Script started on 2017年03月21日 (週二) 14時03分42秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -
error: key does not contain a section: -
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -1[Kl
user.email=sbrad0201@gmail.com
user.name=sbrad0201
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github. com/<your github account>/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[C[C[C[C[C[C[C[1P/lab1.git[C[C[C[C[C[C[1P/lab1.git[C[C[C[C[C[1P/lab1.git[C[C[C[Cd/lab1.git[C[C[C[C[C[1P/lab1.git[C[C[C[Cs/lab1.git[C[C[C[C[Cb/lab1.git[C[C[C[C[C[Cr/lab1.git[C[C[C[C[C[C[Ca/lab1.gitd/lab1.git0/lab1.git2/lab1.git0/lab1.git1/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月21日 (週二) 14時04分42秒
